services:
  db:
    image: mariadb:10.11
    container_name: lodo-db-local
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: lodo_db
      MYSQL_USER: lodo_user
      MYSQL_PASSWORD: lodo_password
    ports:
      - "3307:3306" # Usamos 3307 local para no chocar con un MySQL que ya tengas

  backend:
    build: ./backend
    container_name: lodo-back-local
    ports:
      - "8080:8080"
    environment:
      DB_USER: lodo_user
      DB_PASS: lodo_password
      DB_HOST: db # Docker reconoce el nombre del servicio 'db'
      DB_PORT: 3306
      DB_NAME: lodo_db
    depends_on:
      - db

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8080 # En local apunta al back local
    container_name: lodo-front-local
    ports:
      - "80:80"
    depends_on:
      - backend